# Generated by Django 4.1 on 2022-12-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=200, unique=True)),
                ('phone_no', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
