# Generated by Django 4.1 on 2022-12-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app1', '0002_rename_cust_name_customer_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
